GO
CREATE PROC SP_SELECTALLSINHVIEN
AS
SELECT * FROM SINHVIEN
--XÓA
GO
CREATE PROC SP_DELETESINHVIEN(@MSSV NVARCHAR (25))
AS
BEGIN
DELETE FROM SINHVIEN WHERE MSSV=@MSSV 
END
--THÊM
GO
CREATE PROC SP_ADDSINHVIEN(@MSSV NVARCHAR (25) , @HOTEN NVARCHAR (50), @PHAI NVARCHAR (10), @NGAYSINH DATETIME)
AS 
BEGIN
INSERT INTO SINHVIEN(MSSV, HOTEN, PHAI, NGAYSINH)
VALUES(@MSSV,@HOTEN, @PHAI, @NGAYSINH)
END
--SỬA
GO
CREATE PROC SP_UPDATESINHVIEN(@MSSV NVARCHAR (25) , @HOTEN NVARCHAR (50), @PHAI NVARCHAR(10), @NGAYSINH DATETIME)
AS
BEGIN
UPDATE SINHVIEN SET HOTEN=@HOTEN WHERE MSSV=@MSSV
UPDATE SINHVIEN SET PHAI=@PHAI WHERE MSSV=@MSSV
UPDATE SINHVIEN SET NGAYSINH=@NGAYSINH WHERE MSSV=@MSSV
END
-- LẤY TÊN
--GO
--CREATE PROC SP_LAYTENLOAI(@MALOAI NVARCHAR (14))
--AS
--BEGIN
--SELECT TENLOAI FROM LOAIXE WHERE MALOAI=@MALOAI 
--END
-- TÌM KIẾM
GO
CREATE PROC SP_TIMKIEMSINHVIEN(@MSSV NVARCHAR (25))
AS
BEGIN
SELECT * FROM SINHVIEN WHERE MSSV=@MSSV
END 