GO
create database QLSinhVien
GO
use QLSinhVien
--TAO BANG
GO
CREATE TABLE SINHVIEN(MSSV NVARCHAR (25) NOT NULL, HOTEN NVARCHAR (50), PHAI NVARCHAR (10), NGAYSINH DATETIME)
--KHOA CHINH
GO
ALTER TABLE SINHVIEN ADD CONSTRAINT PK_SINHVIEN PRIMARY KEY (MSSV)
--KHOA NGOAI
--ALTER TABLE SINHVIEN ADD CONSTRAINT FK_ FOREIGN KEY(...) REFERENCES ... (...)

ALTER TABLE SINHVIEN ADD CONSTRAINT UNI_SINHVIEN UNIQUE (MSSV)
ALTER TABLE SINHVIEN ADD CONSTRAINT PHAI CHECK (PHAI = N'NAM' OR PHAI = N'NỮ')