<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Product extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            ['id' => 1, 'picture_Product' => 'product-01.jpg', 'name_Product' => 'Esprit Ruffle Shirt', 'price_Product' => 16.64, 'size_Product' => 'S', 'color_Product' => 'White', 'weight_Product' => '0.29 kg', 'dimensisons_Product' => '110 x 33 x 100 cm', 'materials_Product' => 'spandex', 'description_Product' => 'Stay cool and dry in the Russell Athletic Dri-Power Core Performance Long Sleeve Tee while in the gym, on the court, or on the field. This men is long sleeve T-shirt has a relaxed fit for complete comfort.'],
            ['id' => 2, 'picture_Product' => 'product-02.jpg', 'name_Product' => 'Herschel supply', 'price_Product' => 35.31, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.35 kg', 'dimensisons_Product' => '100 x 23 x 90 cm', 'materials_Product' => '60% cotton', 'description_Product' => 'This boat-neck top makes a statement in seaworthy stripes and a feminine cut, slit at the hem for smooth movement.'],
            ['id' => 3, 'picture_Product' => 'product-03.jpg', 'name_Product' => 'Only Check Trouser', 'price_Product' => 25.50, 'size_Product' => 'L', 'color_Product' => 'Blue', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '98% Cotton', 'description_Product' => 'Made with Organic Content Standard (OCS) 100 certified organic cotton and certified carbon neutral by ClimatePartner. Learn about our third party sustainability certifications below.'],
            ['id' => 4, 'picture_Product' => 'product-04.jpg', 'name_Product' => 'Classic Trench Coat', 'price_Product' => 75.00, 'size_Product' => 'S', 'color_Product' => 'Brown', 'weight_Product' => '0.55 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '50% Cotton, 40% Polyester, 10% Nylon', 'description_Product' => 'Focused on creating affordable, high-quality, and long-lasting everyday clothing you can rely on. Our line of women is apparel includes cashmere sweaters, fleece and down jackets, and more, including plus-size options. Our consistent sizing takes the guesswork out of shopping, and each piece is put to the test to maintain the highest standards in quality and comfort.'],
            ['id' => 5, 'picture_Product' => 'product-05.jpg', 'name_Product' => 'Front Pocket Jumper', 'price_Product' => 34.75, 'size_Product' => 'L', 'color_Product' => 'Gray', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '77% Cotton, 21% Polyester', 'description_Product' => 'Made with Organic Content Standard (OCS) 100 certified organic cotton and certified carbon neutral by ClimatePartner. Learn about our third party sustainability certifications below.These are the double-front denim bibs you will be wearing for years to come. Bring on the mud, paint, and grass stains.'],
            ['id' => 6, 'picture_Product' => 'product-06.jpg', 'name_Product' => 'Vintage Inspired Classic', 'price_Product' => 93.20, 'size_Product' => '28mm', 'color_Product' => 'Black', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '3 x 3 x 3 cm', 'materials_Product' => 'metal', 'description_Product' => 'Create the lifestyle that gives you confidence with the help of our sports smartwatch for women and men. With smart features like music controls, weather forecast and push notifications – you have everything you need to come back stronger.'],
            ['id' => 7, 'picture_Product' => 'product-07.jpg', 'name_Product' => 'Shirt in Stretch Cotton', 'price_Product' => 52.66, 'size_Product' => 'L', 'color_Product' => 'Brown', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Cotton', 'description_Product' => 'We listen to customer feedback and fine-tune every detail to ensure our clothes are more comfortable, higher quality, and longer lasting—at affordable prices for the whole family.'],
            ['id' => 8, 'picture_Product' => 'product-08.jpg', 'name_Product' => 'Pieces Metallic Printed', 'price_Product' => 18.96, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '60% Polyester, 30% Cotton, 10% Rayon', 'description_Product' => 'Love today is trendy graphic tees do not miss out on this one. It is soft, feminine, flattering...and available in your pick of pretty prints.'],
            ['id' => 9, 'picture_Product' => 'product-09.jpg', 'name_Product' => 'Converse All Star Hi Plimsolls', 'price_Product' => 75.00, 'size_Product' => '40', 'color_Product' => 'Black', 'weight_Product' => '0.35 kg', 'dimensisons_Product' => '13 x 4 x 5 inches', 'materials_Product' => 'blank', 'description_Product' => 'The chuck taylor all star low top sneaker is the pioneer of laidback style, sporting the classic canvas upper and iconic silhouette. In soft, standout hues, this design has never been sweeter. Updated with a durable outsole. Ortholite insole for cushioning takes comfort to the next level. Ortholite is a trademark of O2 partners, llc.'],
            ['id' => 10, 'picture_Product' => 'product-10.jpg', 'name_Product' => 'Femme T-Shirt In Stripe', 'price_Product' => 25.85, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Cotton', 'description_Product' => 'Crafted from super-soft cotton jersey, the classic tee never gets old. Own one in every color for casual style, dressed up or down any day of the year.'],
            ['id' => 11, 'picture_Product' => 'product-11.jpg', 'name_Product' => 'Herschel shirt', 'price_Product' => 63.16, 'size_Product' => 'L', 'color_Product' => 'Blue', 'weight_Product' => '0.05 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '98% Cotton', 'description_Product' => 'Made from a lightweight cotton and elastane blend, this classic oxford shirt is the perfect staple with just the right amount of comfort stretch. Made with Organic Content Standard (OCS) 100 certified organic cotton and certified carbon neutral by ClimatePartner. Learn about our third party sustainability certifications below.'],
            ['id' => 12, 'picture_Product' => 'product-12.jpg', 'name_Product' => 'Herschel belt', 'price_Product' => 63.15, 'size_Product' => 'none', 'color_Product' => 'Brown', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 cm', 'materials_Product' => 'blank', 'description_Product' => ' This fashion belt is enclosed in a sleek and modern gift box, which make it a great gift for boyfriend, father and male colleagues as birthday gift or anniversary gift.'],
            ['id' => 13, 'picture_Product' => 'product-13.jpg', 'name_Product' => 'T-Shirt with Sleeve', 'price_Product' => 18.50, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Cotton', 'description_Product' => 'This Hanes Nano t-shirt for women is so light and soft you will fall in love with it. Ultra-light 100 percent ring-spun cotton jersey feels great on your skin and drapes beautifully.'],
            ['id' => 14, 'picture_Product' => 'product-14.jpg', 'name_Product' => 'Pretty Little Thing', 'price_Product' => 54.79, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.2 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '90% Cotton, 10% Polyester', 'description_Product' => 'Sometimes you want style. Other times you want comfort. The Gildan Softstyle Ladies’ T-Shirt offers both. Made from 4.5 oz. per sq. yd. fabric, this fitted silhouette jersey knit provides a fashionable look and soft feel that you’ll love the first time you put it on. With double-needle sleeve and bottom hems, and a high-stitch density, this durably constructed Tee also makes for a smooth printing surface.'],
            ['id' => 15, 'picture_Product' => 'product-15.jpg', 'name_Product' => 'Mini Silver Mesh Watch', 'price_Product' => 86.50, 'size_Product' => '36mm', 'color_Product' => 'Black', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '5 x 5 x 5 cm', 'materials_Product' => 'metal', 'description_Product' => 'The direct descendant of our 1960s televised torture test survivors, today is Easy Reader is as durable as it is classically cool.'],
            ['id' => 16, 'picture_Product' => 'product-16.jpg', 'name_Product' => 'Square Neck Back', 'price_Product' => 29.50, 'size_Product' => 'S', 'color_Product' => 'Gray', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'We listen to customer feedback and fine-tune every detail to ensure our clothes are more comfortable, higher quality, and longer lasting—at affordable prices for the whole family.'],
            ['id' => 17, 'picture_Product' => 'product-17.jpg', 'name_Product' => 'Men s Polo Shirt with Oysters and Shoulders', 'price_Product' => 10.50, 'size_Product' => 'S', 'color_Product' => 'Gray', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'The new product line is researched by YODY, applying modern new technology in the production process. Accordingly, oyster polo shirts that have undergone rigorous processing have possessed many outstanding features.'],
            ['id' => 18, 'picture_Product' => 'product-18.jpg', 'name_Product' => 'Coolmax Lacoste Men s Polo Shirt', 'price_Product' => 20.50, 'size_Product' => 'S', 'color_Product' => 'Blue', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'The design of the men s polo shirt is basic, so it is easy to wear for everyone. Men s polo shirt with a straight form will help you to wear it comfortably every day, confident in all activities.'],
            ['id' => 19, 'picture_Product' => 'product-19.jpg', 'name_Product' => 'Coolmax Lacoste Women s Polo Shirt', 'price_Product' => 25.50, 'size_Product' => 'M', 'color_Product' => 'Blue', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'The design of the women s polo shirt is basic, so it is easy to wear for everyone. Women s polo shirt with a wide form will help you to wear it comfortably every day, confidently in all activities.'],
            ['id' => 20, 'picture_Product' => 'product-20.jpg', 'name_Product' => 'Gingham Pattern Puff Short Sleeve Croptop Shirt', 'price_Product' => 17.70, 'size_Product' => 'S', 'color_Product' => 'Gray', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'Crop top style shirt has always been a favorite friend of YODY followers in recent seasons.'],
            ['id' => 21, 'picture_Product' => 'product-21.jpg', 'name_Product' => 'Women s Shirts Loose Neckline', 'price_Product' => 15.50, 'size_Product' => 'S', 'color_Product' => 'White', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '64% Polyester, 33% Rayon, 3% Spandex', 'description_Product' => 'Cotton shirt for summer fresh.Soft, light, airy material.'],
            ['id' => 22, 'picture_Product' => 'product-22.jpg', 'name_Product' => 'Stylized Round Neck Women s Sleeveless Shirt', 'price_Product' => 19.50, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Polyester- Finishing by Bio Protein', 'description_Product' => 'Bio Protein technology makes the fabric soft and smooth, catches light light to create a luxurious and elegant look. Friendly and safe for the wearer, prevents dirt from sticking to the surface of the fabric. Fashion design is wide, thin and light, padded shoulder straps. strong, firm but still retain the soft femininity.'],
            ['id' => 23, 'picture_Product' => 'product-23.jpg', 'name_Product' => 'Women s Sports Windbreaker Ribs Soup', 'price_Product' => 30.60, 'size_Product' => 'L', 'color_Product' => 'Blue', 'weight_Product' => '0.15 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '100% Polyester', 'description_Product' => 'Youthful design with soup on the sides, soft feminine cut.'],
            ['id' => 24, 'picture_Product' => 'product-24.jpg', 'name_Product' => 'Dynamic Melange Women s Sports T-Shirt', 'price_Product' => 25.50, 'size_Product' => 'S', 'color_Product' => 'Blue', 'weight_Product' => '0.27 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '45% Polyester, 45% Nylon, 10% Spandex', 'description_Product' => 'Stretchy, effective form keeping for you to move freely. High durability, color fastness during use. Unique color-matching melange effect.'],
            ['id' => 25, 'picture_Product' => 'product-25.jpg', 'name_Product' => 'Young Office Men Nano Vest', 'price_Product' => 45.00, 'size_Product' => 'M', 'color_Product' => 'Blue', 'weight_Product' => '0.25 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Nanotechnology polyester', 'description_Product' => 'Narrow lapel with buttonhole detail. Lapels are fastened with two front buttons. The front body has two symmetrical pockets and an inner pocket for important items such as wallets and cards. Buttons on the cuffs have floating buttons. Slim Fit, medium Twisted with chest and waist, and sleeves.'],
            ['id' => 26, 'picture_Product' => 'product-26.jpg', 'name_Product' => 'Men s Sports Printed T-shirt Work Out', 'price_Product' => 20.50, 'size_Product' => 'M', 'color_Product' => 'Black', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Stretchy sports fabric, not too thick', 'description_Product' => 'Absorb sweat, cool, suitable for outdoor activities in summer. Elegant round neck design, loose shirt form easily conceals body flaws. The print on the chest creates a highlight for the shirt. Pair with jeans, shorts,...'],
            ['id' => 27, 'picture_Product' => 'product-27.jpg', 'name_Product' => 'Men s jeans QJDTK237', 'price_Product' => 30.20, 'size_Product' => 'S', 'color_Product' => 'Blue', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => ' Jeans cotton', 'description_Product' => 'Has high sweat absorption and moisture absorption, cool.'],
            ['id' => 28, 'picture_Product' => 'product-28.jpg', 'name_Product' => 'DAZY Lotus leaf border dress', 'price_Product' => 40.50, 'size_Product' => 'L', 'color_Product' => 'Blue ', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => '80% Cotton, 20% Polyamide', 'description_Product' => 'Lotus Leaf Balls Front bows in plain color Cute.'],
            ['id' => 29, 'picture_Product' => 'product-29.jpg', 'name_Product' => 'WEATHER DRESS', 'price_Product' => 25.00, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic poly', 'description_Product' => 'Female model measurements: Height: 168cm. Measurements of 3 rounds: 83 - 59 - 86 (Wearing size S).'],
            ['id' => 30, 'picture_Product' => 'product-30.jpg', 'name_Product' => 'Women s Cafe Polo Shirt with Raglan Sleeves', 'price_Product' => 22.50, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Polo Cafe', 'description_Product' => 'Exclusive Polo Cafe fabric is super light and cool. The material has the ability to effectively deodorize and resist UV rays, protecting the skin. Color-coordinated cafe polo shirt with a youthful, dynamic, and flattering shape. Bear motifs are meticulous in every detail, creating an impressive and outstanding image.'],
            ['id' => 31, 'picture_Product' => 'product-31.jpg', 'name_Product' => 'SLIM DRESS WITH BELT D12942', 'price_Product' => 20.50, 'size_Product' => 'X', 'color_Product' => 'Orange', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic Fabric', 'description_Product' => 'Sleeveless shirt dress, plain brown tone, combined with pocket flaps.'],
            ['id' => 32, 'picture_Product' => 'product-32.jpg', 'name_Product' => 'DESIGNED BLUE DRESS D15622', 'price_Product' => 30.50, 'size_Product' => 'S', 'color_Product' => 'Green', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic Fabric', 'description_Product' => 'Knee-length A-line dress, solid blue tone, stylized vest neck.'],
            ['id' => 33, 'picture_Product' => 'product-33.jpg', 'name_Product' => 'Sleeveless T-shirt TS13562', 'price_Product' => 25.50, 'size_Product' => 'M', 'color_Product' => 'White', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Spandex', 'description_Product' => 'T-shirt with round neck design, plain white tone combined with silk material hands, printed with baby flower motifs.'],
            ['id' => 34, 'picture_Product' => 'product-34.jpg', 'name_Product' => 'WHITE T-shirt TS60212', 'price_Product' => 40.50, 'size_Product' => 'S', 'color_Product' => 'White', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Spandex', 'description_Product' => 'T-shirt design with short sleeves, round neck, white tone combined with sharp prints.'],
            ['id' => 35, 'picture_Product' => 'product-35.jpg', 'name_Product' => 'LEATHER LEATHER SIZE SM15552', 'price_Product' => 35.50, 'size_Product' => 'S', 'color_Product' => 'Brown', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Short-sleeved shirt, round neck, combined with brown leather texture.'],
            ['id' => 36, 'picture_Product' => 'product-36.jpg', 'name_Product' => 'WHITE COLLEGE SIZE SM01012', 'price_Product' => 21.50, 'size_Product' => 'L', 'color_Product' => 'White', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Short-sleeve design shirt, collar with embroidered flowers, plain white tone.'],
            ['id' => 37, 'picture_Product' => 'product-37.jpg', 'name_Product' => 'SUNSHIPS WITH CODE ACN60072', 'price_Product' => 23.10, 'size_Product' => 'S', 'color_Product' => 'Pink', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => '​Sunwear with a hood, high zipper for maximum protection, long sleeves with eye holes to protect the back of the hand.'],
            ['id' => 38, 'picture_Product' => 'product-38.jpg', 'name_Product' => 'Pencil skirt Z01372', 'price_Product' => 45.00, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => '​Pencil skirt with high waisted design, solid black tone.'],
            ['id' => 39, 'picture_Product' => 'product-39.jpg', 'name_Product' => 'Polka dot dress D03352', 'price_Product' => 27.00, 'size_Product' => 'X', 'color_Product' => 'Blue', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Dress with A-line design, knee length, neckline, shoulder sleeves, cobalt blue tone combined with white polka dot pattern.'],
            ['id' => 40, 'picture_Product' => 'product-40.jpg', 'name_Product' => 'JEANS FRONT SLIDE Z67012', 'price_Product' => 25.50, 'size_Product' => 'S', 'color_Product' => 'Purple', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Pencil skirt with high waisted design, solid black tone.'],
            ['id' => 41, 'picture_Product' => 'product-41.jpg', 'name_Product' => 'WORKSHOP D00702', 'price_Product' => 24.50, 'size_Product' => 'S', 'color_Product' => 'Pink', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'One-piece peplum dress to help conceal round 2, knee-length A-shape, smooth blue tone, light arms.'],
            ['id' => 42, 'picture_Product' => 'product-42.jpg', 'name_Product' => 'BLUE T-shirt TS60202', 'price_Product' => 23.50, 'size_Product' => 'S', 'color_Product' => 'Green', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Spandex', 'description_Product' => 'T-shirt with short sleeves, round neck, blue tone combined with sharp floral prints.'],
            ['id' => 43, 'picture_Product' => 'product-43.jpg', 'name_Product' => 'PEPLUM DESIGN DRESS D03012', 'price_Product' => 22.50, 'size_Product' => 'S', 'color_Product' => 'Green', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Peplum design dress to help conceal round 2, knee-length A-shaped figure, smooth blue tone, light arms.'],
            ['id' => 44, 'picture_Product' => 'product-44.jpg', 'name_Product' => 'WORKSHOP Q12902', 'price_Product' => 20.50, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Pants designed with a straight black tone, stylized waistband.'],
            ['id' => 45, 'picture_Product' => 'product-45.jpg', 'name_Product' => 'DESIGN DRESS D16312', 'price_Product' => 30.50, 'size_Product' => 'S', 'color_Product' => 'Black', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'The dress is designed with a knee-length hug, black tone, a combination of red and brown tones at the neck and sleeves.'],
            ['id' => 46, 'picture_Product' => 'product-46.jpg', 'name_Product' => 'SET OF FLOWERS HW16192', 'price_Product' => 31.00, 'size_Product' => 'S', 'color_Product' => 'Brown', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Synthetic fabric', 'description_Product' => 'Set includes short-sleeved shirt and culottes, combined with outstanding floral motifs.'],
            ['id' => 47, 'picture_Product' => 'product-47.jpg', 'name_Product' => 'Long Sleeve Plaid Round Neck T-shirt', 'price_Product' => 10.50, 'size_Product' => 'S', 'color_Product' => 'Gray', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Fabric', 'description_Product' => 'Loose t-shirt made of durable fabric for a comfortable style.'],
            ['id' => 48, 'picture_Product' => 'product-48.jpg', 'name_Product' => 'Men s T-shirts with Sleeves', 'price_Product' => 30.50, 'size_Product' => 'M', 'color_Product' => 'Brown', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Fabric', 'description_Product' => 'Simple and elegant design but no less elegant elegance. The colors are simple and beautiful, easy to buy and easy to wear. Soft cotton fabric, cool to wear, absorbs sweat.'],
            ['id' => 49, 'picture_Product' => 'product-49.jpg', 'name_Product' => 'Men s long-sleeved shirt GMAN', 'price_Product' => 22.50, 'size_Product' => 'S', 'color_Product' => 'White', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Silk', 'description_Product' => 'High-quality anti-wrinkle, body-hugging, long-sleeved Men s Shirt is a great suggestion for men when choosing clothes every day. With men s shirt designs that are simply designed and exude sophistication, bringing a youthful and dynamic fashion style, it will definitely be the perfect choice for a modern and masculine guy.'],
            ['id' => 50, 'picture_Product' => 'product-50.jpg', 'name_Product' => 'Unisex Clothing Set', 'price_Product' => 15.00, 'size_Product' => 'S', 'color_Product' => 'White', 'weight_Product' => '0.3 kg', 'dimensisons_Product' => '120 x 25 x 95 cm', 'materials_Product' => 'Cotton ', 'description_Product' => 'Stretch cotton fabric, durable, machine washable thanks to 5% Spandex yarn. High-quality form without ruffles, smooth and glossy fabric surface, cool, still suitable for movement.'],
        ]);
    }
}
