/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quanlynhanvien;

/**
 *
 * @author Administrator
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        menuChucNang = new javax.swing.JMenu();
        menuItemQuanLyNhanVien = new javax.swing.JMenuItem();
        menuItemQuanLyTienLuong = new javax.swing.JMenuItem();
        menuHeThong = new javax.swing.JMenu();
        menuItemDangNhap = new javax.swing.JMenuItem();
        menuItemDangKy = new javax.swing.JMenuItem();
        menuItemThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("ỨNG DỤNG QUẢN LÝ NHÂN VIÊN");

        menuChucNang.setText("Chức Năng");

        menuItemQuanLyNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        menuItemQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        menuItemQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuanLyNhanVienActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemQuanLyNhanVien);

        menuItemQuanLyTienLuong.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        menuItemQuanLyTienLuong.setText("Quản Lý Tiền Lương");
        menuItemQuanLyTienLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuanLyTienLuongActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemQuanLyTienLuong);

        menuMain.add(menuChucNang);

        menuHeThong.setText("Hệ Thống");

        menuItemDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        menuItemDangNhap.setText("Đăng Nhập");
        menuItemDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangNhapActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemDangNhap);

        menuItemDangKy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        menuItemDangKy.setText("Đăng Ký");
        menuItemDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangKyActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemDangKy);

        menuItemThoat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        menuItemThoat.setText("Thoát");
        menuHeThong.add(menuItemThoat);

        menuMain.add(menuHeThong);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        new frmQuanLyNhanVien().setVisible(true);
    }//GEN-LAST:event_menuItemQuanLyNhanVienActionPerformed

    private void menuItemQuanLyTienLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuanLyTienLuongActionPerformed
        // TODO add your handling code here:
        new frmQuanLyTienLuong().setVisible(true);
    }//GEN-LAST:event_menuItemQuanLyTienLuongActionPerformed

    private void menuItemDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangNhapActionPerformed
        // TODO add your handling code here:
        new frmDangNhap().setVisible(true);
    }//GEN-LAST:event_menuItemDangNhapActionPerformed

    private void menuItemDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangKyActionPerformed
        // TODO add your handling code here:
        new frmDangKy().setVisible(true);
    }//GEN-LAST:event_menuItemDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuChucNang;
    private javax.swing.JMenu menuHeThong;
    private javax.swing.JMenuItem menuItemDangKy;
    private javax.swing.JMenuItem menuItemDangNhap;
    private javax.swing.JMenuItem menuItemQuanLyNhanVien;
    private javax.swing.JMenuItem menuItemQuanLyTienLuong;
    private javax.swing.JMenuItem menuItemThoat;
    private javax.swing.JMenuBar menuMain;
    // End of variables declaration//GEN-END:variables
}
