# Generated by Django 4.2.5 on 2023-11-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_friendrequest_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='video',
        ),
    ]
