# Generated by Django 4.2.5 on 2023-11-13 01:37

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_messagegroup_joinrequest_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image2',
            field=models.ImageField(blank=True, default='cover.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
