# Generated by Django 4.2.5 on 2023-11-17 00:22

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_group_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_page',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
