# Generated by Django 4.2.5 on 2023-11-29 06:49

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
