# Generated by Django 4.2.5 on 2023-11-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_chatmessage_image_chatmessage_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='video',
        ),
    ]
