GO
CREATE DATABASE QLPhanCongGiangDay
GO
USE QLPhanCongGiangDay
-- BẢNG GIANGVIEN
CREATE TABLE GIANGVIEN (MaGV NVARCHAR(10) NOT NULL, HoTen NVARCHAR(50) NOT NULL, MaBM NVARCHAR(10) NOT NULL PRIMARY KEY (MaGV));

-- BẢNG HOCPHAN
CREATE TABLE HOCPHAN (MaHP NVARCHAR(10) NOT NULL, TenHP NVARCHAR(50) NOT NULL,HocKy INT NOT NULL, SoTC INT NOT NULL, SoTiet INT NOT NULL, MaBM NVARCHAR(10) NOT NULL PRIMARY KEY (MaHP));

-- BẢNG BOMON
CREATE TABLE BOMON (MaBM NVARCHAR(10) NOT NULL, TenBM NVARCHAR(50) NOT NULL, MaKhoa NVARCHAR(10) NOT NULL PRIMARY KEY(MaBM));

-- BẢNG KHOA
CREATE TABLE KHOA (MaKhoa NVARCHAR(10) NOT NULL,TenKhoa NVARCHAR(50) PRIMARY KEY(MaKhoa));

-- BANG PHANCONGNHOM
-- CREATE TABLE PHANCONGNHOM (MaHP NVARCHAR(10) NOT NULL,NHOM INT, MaGV NVARCHAR(10) NOT NULL, HocKy INT  PRIMARY KEY(MaHP));

-- khoa ngoại GIANGVIEN VÀ BOMON
ALTER TABLE GIANGVIEN ADD CONSTRAINT FK_GV_BM FOREIGN KEY(MaBM) REFERENCES BOMON(MaBM)

-- khoa ngoại HOCPHAN VÀ BOMON
ALTER TABLE HOCPHAN ADD CONSTRAINT FK_HP_BM FOREIGN KEY(MaBM) REFERENCES BOMON(MaBM)

-- khoa ngoại HOCPHAN VÀ BOMON
ALTER TABLE BOMON ADD CONSTRAINT FK_BM_KHOA FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa)
-- khoa ngoại HOCPHAN VÀ PHANCONGNHOM
-- ALTER TABLE PHANCONGNHOM ADD CONSTRAINT FK_PCN_HP FOREIGN KEY(MaHP) REFERENCES HOCPHAN(MaHP)
-- khoa ngoại HOCPHAN VÀ PHANCONGNHOM
-- ALTER TABLE PHANCONGNHOM ADD CONSTRAINT FK_PCN_GV FOREIGN KEY(MaGV) REFERENCES GIANGVIEN(MaGV)


-- CHECK
ALTER TABLE HOCPHAN ADD CONSTRAINT SoTiet CHECK (SoTiet >= 30 and SoTiet <= 90)
ALTER TABLE HOCPHAN ADD CONSTRAINT SoTC CHECK (SoTC >= 1 and SoTC <= 6)

