/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlynhanvien;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Luong;
import model.NhanVien;
import model.QuanLyLuong;
import model.QuanLyNhanVien;

/**
 *
 * @author Hoaan
 */
public class frmTimKiem extends javax.swing.JFrame {

    /**
     * Creates new form frmTimKiem
     */
    public frmTimKiem() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSachNV = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDanhSachBL = new javax.swing.JTable();
        btnTraLuong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaBL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("TÌM KIẾM NHÂN VIÊN");

        jLabel2.setText("Mã Nhân Viên:");

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbDanhSachNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ Tên", "Năm Sinh", "Giới Tính", "Địa Chỉ", "SĐT", "Chức Vụ"
            }
        ));
        jScrollPane1.setViewportView(tbDanhSachNV);

        tbDanhSachBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Mã BL", "Lương Cơ Bản", "Lương Thưởng", "Hệ Số Lương", "Tháng", "Năm", "Tổng Lương Tháng", "Tình Trạng"
            }
        ));
        jScrollPane2.setViewportView(tbDanhSachBL);

        btnTraLuong.setText("Trả Lương");
        btnTraLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraLuongActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã BL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(txtMaBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 334, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnTraLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTraLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    QuanLyNhanVien qlnv = new QuanLyNhanVien();
    QuanLyLuong qll = new QuanLyLuong();
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText();
        ArrayList<NhanVien> data = qlnv.TimKiemNV(maNV);
        ArrayList<Luong> data2 = qll.TimKiemBL(maNV);
        if (qlnv.TimKiemNV(maNV) != null) {
            JOptionPane.showMessageDialog(this, "Tìm thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }
        DefaultTableModel tableModel = (DefaultTableModel) tbDanhSachNV.getModel();
        tableModel.setColumnCount(0);
        tableModel.setRowCount(0);
        tableModel.addColumn("Mã NV");
        tableModel.addColumn("Họ Tên");
        tableModel.addColumn("Năm Sinh");
        tableModel.addColumn("Giới Tính");
        tableModel.addColumn("Địa Chỉ");
        tableModel.addColumn("SĐT");
        tableModel.addColumn("Chức Vụ");
        for (NhanVien nv : data) {
            String chucVu = "";
            String maCV = nv.getMaCV();
            if (maCV.equals("TP")) {
                chucVu = "Trưởng Phòng";
            } else if (maCV.equals("QL")) {
                chucVu = "Quản Lý";
            } else if (maCV.equals("NV")) {
                chucVu = "Nhân Viên";
            }
            tableModel.addRow(new Object[]{nv.getMaNV(), nv.getHoTen(), nv.getNamSinh(), nv.getGioiTinh(), nv.getDiaChi(), nv.getSDT(), chucVu});
        }
        DefaultTableModel tableModel2 = (DefaultTableModel) tbDanhSachBL.getModel();
        tableModel2.setColumnCount(0);
        tableModel2.setRowCount(0);
        tableModel2.addColumn("Mã NV");
        tableModel2.addColumn("Mã Bảng Lương");
        tableModel2.addColumn("Lương Cơ Bản");
        tableModel2.addColumn("Lương Thưởng");
        tableModel2.addColumn("Hệ Số Lương");
        tableModel2.addColumn("Tháng");
        tableModel2.addColumn("Năm");
        tableModel2.addColumn("Tổng Lương Tháng");
        tableModel2.addColumn("Tình Trạng");
        for (Luong luong : data2) {
            String tinhTrangLT = "";
            if (luong.getTinhTrang() == 0) {
                tinhTrangLT = "Chưa trả";
            } else if (luong.getTinhTrang() == 1) {
                tinhTrangLT = "Đã trả";
            }
            tableModel2.addRow(new Object[]{luong.getMaNV(), luong.getMaBL(), luong.getLuongCB(), luong.getLuongThuong(), luong.getHeSL(), luong.getThang(), luong.getNam(), luong.getTongLT(), tinhTrangLT});
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTraLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraLuongActionPerformed
        // TODO add your handling code here:
        String maBL = txtMaBL.getText();
        qll.SuaTinhTrang(maBL);
        if (qll.SuaTinhTrang(maBL) != 0) {
            JOptionPane.showMessageDialog(this, "Trả thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Trả không thành công!");
        }
    }//GEN-LAST:event_btnTraLuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTimKiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTraLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDanhSachBL;
    private javax.swing.JTable tbDanhSachNV;
    private javax.swing.JTextField txtMaBL;
    private javax.swing.JTextField txtMaNV;
    // End of variables declaration//GEN-END:variables
}
