GO
CREATE PROC SP_SELECTALLCTPN
AS
SELECT * FROM CTPN
GO
CREATE PROC SP_SELECTALLCTPX
AS
SELECT * FROM CTPX
GO
CREATE PROC SP_SELECTALLKH
AS
SELECT * FROM KH
GO
CREATE PROC SP_SELECTALLKM
AS
SELECT * FROM KM
GO
CREATE PROC SP_SELECTALLLOAIXE
AS
SELECT * FROM LOAIXE
GO
CREATE PROC SP_SELECTALLNHACC
AS
SELECT * FROM NHACC
GO
CREATE PROC SP_SELECTALLNV
AS
SELECT * FROM NV
GO
CREATE PROC SP_SELECTALLPN
AS
SELECT * FROM PN
GO
CREATE PROC SP_SELECTALLPX
AS
SELECT * FROM PX
GO
CREATE PROC SP_SELECTALLTHUE
AS
SELECT * FROM THUE
GO
CREATE PROC SP_SELECTALLXE
AS
SELECT * FROM XE






GO
CREATE PROC SP_DELETEXE(@MAXE NVARCHAR (14))
AS
BEGIN
DELETE FROM XE WHERE MAXE=@MAXE 
END
GO
CREATE PROC SP_DELETETHUE(@MATHUE NVARCHAR (14))
AS
BEGIN
DELETE FROM THUE WHERE MATHUE=@MATHUE 
END
GO
CREATE PROC SP_DELETEPX(@MAPX NVARCHAR (14))
AS
BEGIN
DELETE FROM PX WHERE MAPX=@MAPX 
END
GO
CREATE PROC SP_DELETEPN(@MAPN NVARCHAR (14))
AS
BEGIN
DELETE FROM PN WHERE MAPN=@MAPN 
END
GO
CREATE PROC SP_DELETENV(@MANV NVARCHAR (14))
AS
BEGIN
DELETE FROM NV WHERE MANV=@MANV 
END
GO
CREATE PROC SP_DELETENHACC(@MANHACC NVARCHAR (14))
AS
BEGIN
DELETE FROM NHACC WHERE MANHACC=@MANHACC 
END
GO
CREATE PROC SP_DELETELOAIXE(@MALOAI NVARCHAR (14))
AS
BEGIN
DELETE FROM LOAIXE WHERE MALOAI=@MALOAI 
END
GO
CREATE PROC SP_DELETEKM(@MAKM NVARCHAR (14))
AS
BEGIN
DELETE FROM KM WHERE MAKM=@MAKM 
END
GO
CREATE PROC SP_DELETEKH(@MAKH NVARCHAR (14))
AS
BEGIN
DELETE FROM KH WHERE MAKH=@MAKH 
END
GO
CREATE PROC SP_DELETECPTN(@MAPN NVARCHAR (14),@MAXE NVARCHAR (14))
AS
BEGIN
DELETE FROM CTPN WHERE MAPN=@MAPN AND MAXE=@MAXE  
END

GO
CREATE PROC SP_DELETECTPX(@MAPX NVARCHAR (14), @MAXE NVARCHAR(14))
AS
BEGIN
DELETE FROM CTPX WHERE MAPX=@MAPX AND MAXE=@MAXE 
END



GO
CREATE PROC SP_ADDXE(@MAXE NVARCHAR (14) , @TENXE NVARCHAR (50), @GIA INT, @SL INT, @NAMSX INT, @NOISX NVARCHAR (50), @MALOAI NVARCHAR (14))
AS 
BEGIN
INSERT INTO XE(MAXE, TENXE, GIA, SL, NAMSX, NOISX, MALOAI)
VALUES(@MAXE,@TENXE, @GIA, @SL, @NAMSX, @NOISX, @MALOAI)
END

GO
CREATE PROC SP_ADDTHUE(@MATHUE NVARCHAR (14), @GIATHUE INT, @MAPN NVARCHAR (14))
AS 
BEGIN
INSERT INTO THUE (MATHUE, GIATHUE, MAPN)
VALUES(@MATHUE, @GIATHUE, @MAPN)
END

GO
CREATE PROC SP_ADDPX(@MAPX NVARCHAR (14) , @NGAYXUAT DATETIME, @MANV NVARCHAR (14), @MAKH NVARCHAR (14))
AS 
BEGIN
INSERT INTO PX (MAPX, NGAYXUAT,MANV, MAKH)
VALUES(@MAPX, @NGAYXUAT,@MANV, @MAKH)
END

GO
CREATE PROC SP_ADDPN(@MAPN NVARCHAR (14) , @NGAYNHAP DATETIME, @MANV NVARCHAR (14))
AS 
BEGIN
INSERT INTO PN (MAPN, NGAYNHAP, MANV)
VALUES(@MAPN, @NGAYNHAP, @MANV)
END


GO
CREATE PROC SP_ADDNV(@MANV NVARCHAR (14),@TENNV NVARCHAR (50), @PHAI NVARCHAR (10), @NGAYSINH DATETIME, @LUONG INT, @MALOAI NVARCHAR (14))
AS 
BEGIN
INSERT INTO NV (MANV, TENNV, PHAI, NGAYSINH, LUONG, MALOAI)
VALUES(@MANV, @TENNV, @PHAI, @NGAYSINH, @LUONG, @MALOAI)
END


GO
CREATE PROC SP_ADDNHACC(@MANHACC NVARCHAR (14), @TENNHACC NVARCHAR (50), @DIACHINCC NVARCHAR (50), @MAPN NVARCHAR (14))
AS 
BEGIN
INSERT INTO NHACC (MANHACC, TENNHACC, DIACHINCC, MAPN)
VALUES(@MANHACC, @TENNHACC, @DIACHINCC, @MAPN)
END


GO
CREATE PROC SP_ADDLOAIXE(@MALOAI NVARCHAR (14), @TENLOAI NVARCHAR (50), @PK NVARCHAR (10))
AS 
BEGIN
INSERT INTO LOAIXE (MALOAI, TENLOAI, PK)
VALUES(@MALOAI, @TENLOAI, @PK)
END


GO
CREATE PROC SP_ADDKM(@MAKM NVARCHAR (14), @NGAYHH DATETIME, @PHANTRAMKM INT, @MAXE NVARCHAR (14))
AS 
BEGIN
INSERT INTO KM (MAKM, NGAYHH, PHANTRAMKM, MAXE)
VALUES(@MAKM, @NGAYHH, @PHANTRAMKM, @MAXE)
END


GO
CREATE PROC SP_ADDKH(@MAKH NVARCHAR (14) , @TENKH NVARCHAR (50), @DIACHI NVARCHAR (50), @PHAI NVARCHAR (10))
AS 
BEGIN
INSERT INTO KH (MAKH, TENKH, DIACHI, PHAI)
VALUES(@MAKH, @TENKH, @DIACHI, @PHAI)
END


GO
CREATE PROC SP_ADDCTPX(@MAPX NVARCHAR (14) , @MAXE NVARCHAR (14) , @SL INT, @GIA INT)
AS 
BEGIN
INSERT INTO CTPX (MAPX, MAXE, SL, GIA)
VALUES(@MAPX, @MAXE, @SL, @GIA)
END


GO
CREATE PROC SP_ADDCTPN(@MAPN NVARCHAR (14), @MAXE NVARCHAR (14), @SL INT, @GIA INT)
AS 
BEGIN
INSERT INTO CTPN (MAPN, MAXE, SL, GIA)
VALUES(@MAPN, @MAXE, @SL, @GIA)
END




GO
CREATE PROC SP_UPDATEXE(@MAXE NVARCHAR (14) , @TENXE NVARCHAR (50), @GIA INT, @SL INT, @NAMSX INT, @NOISX NVARCHAR (50), @MALOAI NVARCHAR (14))
AS
BEGIN
UPDATE XE SET TENXE=@TENXE WHERE MAXE=@MAXE
UPDATE XE SET GIA=@GIA WHERE MAXE=@MAXE
UPDATE XE SET SL=@SL WHERE MAXE=@MAXE
UPDATE XE SET NAMSX=@NAMSX WHERE MAXE=@MAXE
UPDATE XE SET NOISX=@NOISX WHERE MAXE=@MAXE
UPDATE XE SET MALOAI=@MALOAI WHERE MAXE=@MAXE
END


GO
CREATE PROC SP_UPDATETHUE(@MATHUE NVARCHAR (14), @GIATHUE INT, @MAPN NVARCHAR (14))
AS
BEGIN
UPDATE THUE SET GIATHUE=@GIATHUE WHERE MATHUE=@MATHUE
UPDATE THUE SET MAPN=@MAPN WHERE MATHUE=@MATHUE
END


GO
CREATE PROC SP_UPDATEPX(@MAPX NVARCHAR (14) , @NGAYXUAT DATETIME, @MANV NVARCHAR (14), @MAKH NVARCHAR (14))
AS
BEGIN
UPDATE PX SET NGAYXUAT=@NGAYXUAT WHERE MAPX=@MAPX
UPDATE PX SET MANV=@MANV WHERE MAPX=@MAPX
UPDATE PX SET MAKH=@MAKH WHERE MAPX=@MAPX
END


GO
CREATE PROC SP_UPDATEPN(@MAPN NVARCHAR (14) , @NGAYNHAP DATETIME, @MANV NVARCHAR (14))
AS
BEGIN
UPDATE PN SET NGAYNHAP=@NGAYNHAP WHERE MAPN=@MAPN
UPDATE PN SET MANV=@MANV WHERE MAPN=@MAPN
END


GO
CREATE PROC SP_UPDATENV(@MANV NVARCHAR (14),@TENNV NVARCHAR (50), @PHAI NVARCHAR (10), @NGAYSINH DATETIME, @LUONG INT, @MALOAI NVARCHAR (14))
AS
BEGIN
UPDATE NV SET TENNV=@TENNV WHERE MANV=@MANV
UPDATE NV SET PHAI=@PHAI WHERE MANV=@MANV
UPDATE NV SET NGAYSINH=@NGAYSINH WHERE MANV=@MANV
UPDATE NV SET LUONG=@LUONG WHERE MANV=@MANV
UPDATE NV SET MALOAI=@MALOAI WHERE MANV=@MANV
END


GO
CREATE PROC SP_UPDATENHACC(@MANHACC NVARCHAR (14), @TENNHACC NVARCHAR (50), @DIACHINCC NVARCHAR (50), @MAPN NVARCHAR (14))
AS
BEGIN
UPDATE NHACC SET TENNHACC=@TENNHACC WHERE MANHACC=@MANHACC
UPDATE NHACC SET DIACHINCC=@DIACHINCC WHERE MANHACC=@MANHACC
UPDATE NHACC SET MAPN=@MAPN WHERE MANHACC=@MANHACC
END


GO
CREATE PROC SP_UPDATELOAIXE(@MALOAI NVARCHAR (14), @TENLOAI NVARCHAR (50), @PK NVARCHAR (10))
AS
BEGIN
UPDATE LOAIXE SET TENLOAI=@TENLOAI WHERE MALOAI=@MALOAI
UPDATE LOAIXE SET PK=@PK WHERE MALOAI=@MALOAI
END


GO
CREATE PROC SP_UPDATEKM(@MAKM NVARCHAR (14), @NGAYHH DATETIME, @PHANTRAMKM INT, @MAXE NVARCHAR (14))
AS
BEGIN
UPDATE KM SET NGAYHH=@NGAYHH WHERE MAKM=@MAKM
UPDATE KM SET PHANTRAMKM=@PHANTRAMKM WHERE MAKM=@MAKM
UPDATE KM SET MAXE=@MAXE WHERE MAKM=@MAKM
END


GO
CREATE PROC SP_UPDATEKH(@MAKH NVARCHAR (14) , @TENKH NVARCHAR (50), @DIACHI NVARCHAR (50), @PHAI NVARCHAR (10))
AS
BEGIN
UPDATE KH SET TENKH=@TENKH WHERE MAKH=@MAKH
UPDATE KH SET DIACHI=@DIACHI WHERE MAKH=@MAKH
UPDATE KH SET PHAI=@PHAI WHERE MAKH=@MAKH
END


GO
CREATE PROC SP_UPDATECTPX(@MAPX NVARCHAR (14), @MAXE NVARCHAR (14),@SL INT,@GIA INT)
AS
BEGIN
UPDATE CTPX SET SL=@SL WHERE MAXE=@MAXE AND MAPX=@MAPX
UPDATE CTPX SET MAPX=@MAPX WHERE MAXE=@MAXE AND MAPX=@MAPX
UPDATE CTPX SET MAXE=@MAXE WHERE MAXE=@MAXE AND MAPX=@MAPX
UPDATE CTPX SET GIA=@GIA WHERE MAXE=@MAXE AND MAPX=@MAPX
END


GO
CREATE PROC SP_UPDATECTPN(@MAPN NVARCHAR (14), @MAXE NVARCHAR (14), @SL INT, @GIA INT)
AS
BEGIN
UPDATE CTPN SET SL=@SL WHERE MAXE=@MAXE AND MAPN=@MAPN
UPDATE CTPN SET MAPN=@MAPN WHERE MAXE=@MAXE AND MAPN=@MAPN
UPDATE CTPN SET MAXE=@MAXE WHERE MAXE=@MAXE AND MAPN=@MAPN
END



GO
CREATE PROC SP_LAYTENLOAI(@MALOAI NVARCHAR (14))
AS
BEGIN
SELECT TENLOAI FROM LOAIXE WHERE MALOAI=@MALOAI 
END 

GO
CREATE PROC SP_LAYTENXE(@MAXE NVARCHAR (14))
AS
BEGIN
SELECT TENXE FROM XE WHERE MAXE=@MAXE 
END  

GO
CREATE PROC SP_LAYTENNHANVIEN(@MANV NVARCHAR (14))
AS
BEGIN
SELECT TENNV FROM NV WHERE MANV=@MANV 
END  

GO
CREATE PROC SP_LAYTENKH(@MAKH NVARCHAR (14))
AS
BEGIN
SELECT TENKH FROM KH WHERE MAKH=@MAKH 
END





GO
CREATE PROC SP_TIMKIEMXE(@MAXE NVARCHAR (14))
AS
BEGIN
SELECT * FROM XE WHERE MAXE=@MAXE
END


GO
CREATE PROC SP_TIMKIEMTHUE(@MATHUE NVARCHAR (14))
AS
BEGIN
SELECT * FROM THUE WHERE MATHUE=@MATHUE
END


GO
CREATE PROC SP_TIMKIEMPX(@MAPX NVARCHAR (14))
AS
BEGIN
SELECT * FROM PX WHERE MAPX=@MAPX
END


GO
CREATE PROC SP_TIMKIEMPN(@MAPN NVARCHAR (14))
AS
BEGIN
SELECT * FROM PN WHERE MAPN=@MAPN
END


GO
CREATE PROC SP_TIMKIEMNV(@MANV NVARCHAR (14))
AS
BEGIN
SELECT * FROM NV WHERE MANV=@MANV
END


GO
CREATE PROC SP_TIMKIEMNHACC(@MANHACC NVARCHAR (14))
AS
BEGIN
SELECT * FROM NHACC WHERE MANHACC=@MANHACC
END


GO
CREATE PROC SP_TIMKIEMLOAIXE(@MALOAI NVARCHAR (14))
AS
BEGIN
SELECT * FROM LOAIXE WHERE MALOAI=@MALOAI
END


GO
CREATE PROC SP_TIMKIEMKH(@MAKH NVARCHAR (14))
AS
BEGIN
SELECT * FROM KH WHERE MAKH=@MAKH
END


GO
CREATE PROC SP_TIMKIEMKM(@MAKM NVARCHAR (14))
AS
BEGIN
SELECT * FROM KM WHERE MAKM=@MAKM
END


GO
CREATE PROC SP_TIMKIEMCTPX(@MAPX NVARCHAR (14), @MAXE NVARCHAR (14))
AS
BEGIN
SELECT * FROM CTPX WHERE MAPX=@MAPX AND MAXE=@MAXE
END


GO
CREATE PROC SP_TIMKIEMCTPN(@MAPN NVARCHAR (14), @MAXE NVARCHAR (14))
AS
BEGIN
SELECT * FROM CTPN WHERE MAPN=@MAPN AND MAXE=@MAXE
END

GO
CREATE PROC LAYHDBAN(@MAKH NVARCHAR (14))
AS
BEGIN
SELECT * FROM PX, KH, CTPX, NV, XE WHERE PX.MAKH=@MAKH AND KH.MAKH=PX.MAKH AND PX.MANV=NV.MANV AND PX.MAPX=CTPX.MAPX AND CTPX.MAXE=XE.MAXE
END

GO
CREATE PROC LAYHDNHAP(@MANHACC NVARCHAR (14))
AS
BEGIN
SELECT * FROM PN, NHACC, CTPN, NV, XE WHERE NHACC.MANHACC=@MANHACC AND NHACC.MAPN=PN.MAPN AND PN.MANV=NV.MANV AND PN.MAPN=CTPN.MAPN AND CTPN.MAXE=XE.MAXE
END