go
create database QLBanXe
go
use QLBanXe
--TAO BANG
go
CREATE TABLE XE(MAXE NVARCHAR (14) NOT NULL, TENXE NVARCHAR (50), GIA INT, SL INT, NAMSX INT, NOISX NVARCHAR (50), MALOAI NVARCHAR (14))
GO
CREATE TABLE LOAIXE(MALOAI NVARCHAR (14) NOT NULL, TENLOAI NVARCHAR (50), PK NVARCHAR (10))
GO
CREATE TABLE NV(MANV NVARCHAR (14) NOT NULL, TENNV NVARCHAR (50), PHAI NVARCHAR (10), NGAYSINH DATETIME, LUONG INT, MALOAI NVARCHAR (14))
GO
CREATE TABLE PX(MAPX NVARCHAR (14) NOT NULL, NGAYXUAT DATETIME, MANV NVARCHAR (14), MAKH NVARCHAR (14))
GO
CREATE TABLE PN(MAPN NVARCHAR (14) NOT NULL, NGAYNHAP DATETIME, MANV NVARCHAR (14))
GO
CREATE TABLE KH(MAKH NVARCHAR (14) NOT NULL, TENKH NVARCHAR (50), DIACHI NVARCHAR (50), PHAI NVARCHAR (10))
GO
CREATE TABLE NHACC(MANHACC NVARCHAR (14) NOT NULL, TENNHACC NVARCHAR (50), DIACHINCC NVARCHAR (50), MAPN NVARCHAR (14))
GO
CREATE TABLE THUE(MATHUE NVARCHAR (14) NOT NULL, GIATHUE INT, MAPN NVARCHAR (14))
GO
CREATE TABLE KM(MAKM NVARCHAR (14) NOT NULL, NGAYHH DATETIME, PHANTRAMKM INT, MAXE NVARCHAR (14))
CREATE TABLE CTPN(MAPN NVARCHAR (14) NOT NULL, MAXE NVARCHAR (14) NOT NULL, SL INT, GIA INT)
CREATE TABLE CTPX(MAPX NVARCHAR (14) NOT NULL, MAXE NVARCHAR (14) NOT NULL, SL INT, GIA INT)
--KHOA CHINH
GO
ALTER TABLE XE ADD CONSTRAINT PK_XE PRIMARY KEY (MAXE)
GO
ALTER TABLE LOAIXE ADD CONSTRAINT PK_LOAIXE PRIMARY KEY (MALOAI)
GO
ALTER TABLE NV ADD CONSTRAINT PK_NV PRIMARY KEY (MANV)
GO
ALTER TABLE PX ADD CONSTRAINT PK_PX PRIMARY KEY (MAPX)
GO
ALTER TABLE PN ADD CONSTRAINT PK_PN PRIMARY KEY (MAPN)
GO
ALTER TABLE KH ADD CONSTRAINT PK_KH PRIMARY KEY (MAKH)
GO
ALTER TABLE NHACC ADD CONSTRAINT PK_NHACC PRIMARY KEY (MANHACC)
GO
ALTER TABLE THUE ADD CONSTRAINT PK_THUE PRIMARY KEY (MATHUE)
GO
ALTER TABLE KM ADD CONSTRAINT PK_MAKM PRIMARY KEY (MAKM)
GO
ALTER TABLE CTPN ADD CONSTRAINT PK_CTPN PRIMARY KEY (MAPN, MAXE)
GO
ALTER TABLE CTPX ADD CONSTRAINT PK_CTPX PRIMARY KEY (MAPX, MAXE)
--KHOA NGOAI
ALTER TABLE XE ADD CONSTRAINT FK_MALOAIXE FOREIGN KEY(MALOAI) REFERENCES LOAIXE (MALOAI)
ALTER TABLE NV ADD CONSTRAINT FK_MALOAIXENV FOREIGN KEY(MALOAI) REFERENCES LOAIXE (MALOAI)
ALTER TABLE PX ADD CONSTRAINT FK_MANVPX FOREIGN KEY (MANV) REFERENCES NV (MANV)
ALTER TABLE PX ADD CONSTRAINT FK_MAKHPX FOREIGN KEY (MAKH) REFERENCES KH (MAKH)
ALTER TABLE PN ADD CONSTRAINT FK_MANVPN FOREIGN KEY (MANV) REFERENCES NV (MANV)
ALTER TABLE NHACC ADD CONSTRAINT FK_MAPNNHACC FOREIGN KEY (MAPN) REFERENCES PN (MAPN)
ALTER TABLE THUE ADD CONSTRAINT FK_MAPNTHUE FOREIGN KEY (MAPN) REFERENCES PN (MAPN)
ALTER TABLE KM ADD CONSTRAINT FK_MAXEKM FOREIGN KEY (MAXE) REFERENCES XE (MAXE)
ALTER TABLE CTPN ADD CONSTRAINT FK_MAPNCTPN FOREIGN KEY (MAPN) REFERENCES PN (MAPN)
ALTER TABLE CTPN ADD CONSTRAINT FK_MAXECTPN FOREIGN KEY (MAXE) REFERENCES XE (MAXE)
ALTER TABLE CTPX ADD CONSTRAINT FK_MAPXCTPX FOREIGN KEY (MAPX) REFERENCES PX (MAPX)
ALTER TABLE CTPX ADD CONSTRAINT FK_MAXECTPX FOREIGN KEY (MAXE) REFERENCES XE (MAXE)
--CHECK
ALTER TABLE XE ADD CONSTRAINT UNI_XE UNIQUE (MAXE)
ALTER TABLE LOAIXE ADD CONSTRAINT UNI_LOAIXE UNIQUE (MALOAI)
ALTER TABLE NV ADD CONSTRAINT UNI_NV UNIQUE (MANV)
ALTER TABLE PX ADD CONSTRAINT UNI_PX UNIQUE (MAPX)
ALTER TABLE PN ADD CONSTRAINT UNI_PN UNIQUE (MAPN)
ALTER TABLE KH ADD CONSTRAINT UNI_KH UNIQUE (MAKH)
ALTER TABLE NHACC ADD CONSTRAINT UNI_NHACC UNIQUE (MANHACC)
ALTER TABLE THUE ADD CONSTRAINT UNI_THUE UNIQUE (MATHUE)
ALTER TABLE KM ADD CONSTRAINT UNI_KM UNIQUE (MAKM)
ALTER TABLE NV ADD CONSTRAINT PHAI CHECK (PHAI = N'NAM' OR PHAI = N'NỮ')
ALTER TABLE NV ADD CONSTRAINT NGAYSINH CHECK (YEAR(GETDATE())-YEAR(NGAYSINH) >=18)
ALTER TABLE XE ADD CONSTRAINT GIA CHECK (GIA >= 0)
ALTER TABLE XE ADD CONSTRAINT SL CHECK (SL >= 0)
ALTER TABLE KM ADD CONSTRAINT PHANTRAMKM CHECK (PHANTRAMKM >= 0)
ALTER TABLE THUE ADD CONSTRAINT THUECHECK CHECK (GIATHUE >= 0)
ALTER TABLE CTPN ADD CONSTRAINT PNSLCHECK CHECK (SL>=0)
ALTER TABLE CTPN ADD CONSTRAINT PNGIACHECK CHECK (GIA>=0)
ALTER TABLE CTPN ADD CONSTRAINT PXSLCHECK CHECK (SL>=0)
ALTER TABLE CTPN ADD CONSTRAINT PXGIACHECK CHECK (GIA>=0)